In [20]:
import pandas as pd
import numpy as np
import csv
import os
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [3]:
folder = 'input_files/'

In [10]:
for files in os.listdir(folder):
    file_name = os.path.join(folder,files)
    df = pd.read_csv(file_name)
    print(df.columns)

Index(['District_name', 'District_code', 'State_code', 'State_name',
       'ASSET_2001', 'ASSET_2003', 'ASSET_2005', 'ASSET_2007', 'ASSET_2009',
       'ASSET_2011', 'ASSET_Actual_2001', 'Formal_EMP_2001', 'LIT_2001',
       'ASSET_change'],
      dtype='object')
Index(['District_name', 'District_code', 'State_code', 'State_name', 'BF_2001',
       'BF_2003', 'BF_2005', 'BF_2007', 'BF_2009', 'BF_2011', 'BF_Actual_2001',
       'Formal_EMP_2001', 'LIT_2001', 'BF_change', 'BF_change_old'],
      dtype='object')
Index(['District_name', 'District_code', 'State_code', 'State_name',
       'EMP_2001', 'EMP_2003', 'EMP_2005', 'EMP_2007', 'EMP_2009', 'EMP_2011',
       'EMP_Actual_2001', 'EMP_change', 'EMP_change_old'],
      dtype='object')
Index(['District_name', 'District_code', 'State_code', 'State_name', 'FC_2001',
       'FC_2003', 'FC_2005', 'FC_2007', 'FC_2009', 'FC_2011', 'FC_Actual_2001',
       'Formal_EMP_2001', 'FC_change', 'FC_change_old'],
      dtype='object')
Index(['District_name', 'District_code', 'State_code', 'State_name',
       'MSL_2001', 'MSL_2003', 'MSL_2005', 'MSL_2007', 'MSL_2009', 'MSL_2011',
       'MSL_Actual_2001', 'MSL_change', 'MSL_change_old'],
      dtype='object')
Index(['District_name', 'District_code', 'State_code', 'State_name',
       'MSW_2001', 'MSW_2003', 'MSW_2005', 'MSW_2007', 'MSW_2009', 'MSW_2011',
       'MSW_Actual_2001', 'MSW_change', 'MSW_change_old'],
      dtype='object')

In [17]:
data_dict = {}
for files in os.listdir(folder):
    file_name = os.path.join(folder,files)
    
    indicator = files.split('.')[0]
    
    if (indicator == 'ASSET'):
        print(indicator)
        columns = [indicator+'_2001', indicator+'_2003', indicator+'_2005', indicator+'_2007', indicator+'_2009', indicator+'_Actual_2001', 'Formal_EMP_2001', 'LIT_2001', indicator+'_change']
        df = pd.read_csv(file_name, usecols=columns)
        print(df.columns)
        data_dict['ASSET'] = df
    
    elif (indicator == 'BF'):
        print(indicator)
        columns = [indicator+'_2001', indicator+'_2003', indicator+'_2005', indicator+'_2007', indicator+'_2009', indicator+'_Actual_2001', 'Formal_EMP_2001', 'LIT_2001', indicator+'_change']
        df = pd.read_csv(file_name, usecols=columns)
        print(df.columns)
        data_dict['BF'] = df
    
    elif (indicator == 'EMP'):
        print(indicator)
        columns = [indicator+'_2001', indicator+'_2003', indicator+'_2005', indicator+'_2007', indicator+'_2009', indicator+'_Actual_2001',indicator+'_change']
        df = pd.read_csv(file_name, usecols=columns)
        print(df.columns)
        data_dict['EMP'] = df
        
    elif (indicator == 'FC'):
        print(indicator)
        columns = [indicator+'_2001', indicator+'_2003', indicator+'_2005', indicator+'_2007', indicator+'_2009', indicator+'_Actual_2001', 'Formal_EMP_2001',indicator+'_change']
        df = pd.read_csv(file_name, usecols=columns)
        print(df.columns)
        data_dict['FC'] = df
        
    elif (indicator == 'MSL'):
        print(indicator)
        columns = [indicator+'_2001', indicator+'_2003', indicator+'_2005', indicator+'_2007', indicator+'_2009', indicator+'_Actual_2001', indicator+'_change']
        df = pd.read_csv(file_name, usecols=columns)
        print(df.columns)
        data_dict['MSL'] = df
        
    elif (indicator == 'MSW'):
        print(indicator)
        columns = [indicator+'_2001', indicator+'_2003', indicator+'_2005', indicator+'_2007', indicator+'_2009', indicator+'_Actual_2001', indicator+'_change']
        df = pd.read_csv(file_name, usecols=columns)
        print(df.columns)
        data_dict['MSW'] = df

ASSET
Index(['ASSET_2001', 'ASSET_2003', 'ASSET_2005', 'ASSET_2007', 'ASSET_2009',
       'ASSET_Actual_2001', 'Formal_EMP_2001', 'LIT_2001', 'ASSET_change'],
      dtype='object')
BF
Index(['BF_2001', 'BF_2003', 'BF_2005', 'BF_2007', 'BF_2009', 'BF_Actual_2001',
       'Formal_EMP_2001', 'LIT_2001', 'BF_change'],
      dtype='object')
EMP
Index(['EMP_2001', 'EMP_2003', 'EMP_2005', 'EMP_2007', 'EMP_2009',
       'EMP_Actual_2001', 'EMP_change'],
      dtype='object')
FC
Index(['FC_2001', 'FC_2003', 'FC_2005', 'FC_2007', 'FC_2009', 'FC_Actual_2001',
       'Formal_EMP_2001', 'FC_change'],
      dtype='object')
MSL
Index(['MSL_2001', 'MSL_2003', 'MSL_2005', 'MSL_2007', 'MSL_2009',
       'MSL_Actual_2001', 'MSL_change'],
      dtype='object')
MSW
Index(['MSW_2001', 'MSW_2003', 'MSW_2005', 'MSW_2007', 'MSW_2009',
       'MSW_Actual_2001', 'MSW_change'],
      dtype='object')

In [22]:
data_dict['BF']

,BF_2001,BF_2003,BF_2005,BF_2007,BF_2009,BF_Actual_2001,Formal_EMP_2001,LIT_2001,BF_change
0,2,2,2,2,2,2,2,1,0
1,2,2,3,2,2,2,2,1,0
2,2,2,2,2,2,2,3,1,0
3,3,1,2,3,3,2,3,1,1
4,2,2,2,2,2,1,2,1,0
5,3,1,2,2,2,1,2,1,0
6,2,3,2,2,3,1,2,1,0
7,2,2,2,2,2,2,2,1,0
8,3,2,2,3,3,2,3,1,1
9,3,2,3,2,3,2,2,1,1
10,2,2,2,2,2,2,2,1,0
11,2,2,2,2,2,1,2,1,0
12,2,2,2,2,2,1,3,1,0
13,3,3,3,1,1,2,3,2,1
14,2,2,2,2,2,1,2,1,1
15,2,3,3,2,2,1,2,3,1
16,3,3,3,2,3,2,3,2,1
17,2,3,2,2,2,1,2,2,1
18,2,3,2,2,2,1,2,2,1
19,3,3,3,3,3,1,2,3,1
20,3,2,2,3,3,1,2,3,1
21,3,3,3,2,3,1,2,2,1
22,2,2,2,2,3,1,3,2,1
23,2,2,2,2,2,1,2,2,1
24,2,2,2,2,2,1,3,3,1
25,3,2,2,3,2,1,3,2,1
26,2,3,1,2,2,1,3,2,1
27,2,3,1,1,1,2,3,2,1
28,2,2,1,1,1,2,3,2,1
29,2,1,1,2,2,1,3,3,1
...,...,...,...,...,...,...,...,...,...
563,1,1,1,1,1,1,3,1,0
564,1,1,1,1,1,1,3,1,0
565,1,1,1,1,1,1,3,1,0
566,3,2,2,3,3,1,3,3,0
567,1,1,1,1,1,1,3,2,0
568,1,1,1,1,1,1,3,1,0
569,1,1,1,1,1,1,3,2,0
570,3,1,1,2,2,1,1,1,0
571,3,1,1,1,2,1,1,1,0
572,1,2,1,2,3,1,2,2,0
573,3,2,2,2,3,1,2,2,0
574,3,2,2,3,3,1,2,2,0
575,3,3,1,3,2,1,2,2,0
576,1,1,1,1,1,1,2,2,0
577,1,1,1,1,1,1,2,2,0
578,1,1,3,1,1,1,3,2,1
579,1,1,1,1,1,1,3,2,0
580,1,1,1,1,1,1,3,2,0
581,1,1,1,1,1,1,3,2,0
582,3,3,1,3,1,1,3,3,1
583,3,2,1,3,1,1,3,2,0
584,3,3,3,3,3,2,3,3,0
585,1,1,1,1,1,1,2,1,0
586,1,1,1,1,1,1,3,2,1
587,3,3,3,3,3,3,3,2,0
588,3,3,3,3,3,3,3,3,0
589,3,3,3,3,3,3,3,3,0
590,3,3,3,3,3,1,3,3,1
591,3,3,3,3,3,1,3,2,1
592,3,3,3,3,3,2,3,3,1